export enum LoginError {
	SUCCESS = "SUCCESS",
	BAD_REQUEST = "BAD_REQUEST",
	EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
	INVALID_PASSWORD = "INVALID_PASSWORD",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
